steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=manikumarquantiphi9/quantiphiauto init -upgrade "]
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=quantiphiauto  -out=plan.out"]    
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=quantiphiauto apply plan.out"]    
  - id: 'tf destroy'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=quantiphiauto plan -destroy -out=plan.out"]    
  - id: 'tf destroy plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=quantiphiauto apply plan.out"]    
options:
  logging: CLOUD_LOGGING_ONLY
